spring.application.name=demo

#Integrando base de datos postgresql
spring.datasources.url=jdbc:postgresql://localhost:5432/xyzBankDB
spring.datasources.username= ADMIN
spring.datasources.password= 123456

spring.batch.jdbc.initialize-schema=always
