spring.application.name=demo

#Integrando base de datos postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/xyzbank
spring.datasource.username=postgres
spring.datasource.password=c1j9r9f3!psql
spring.datasource.driver-class-name=org.postgresql.Driver

spring.batch.jdbc.initialize-schema=always


spring.batch.job.name=transactionJob
